### ISSUE TITLE
Decryption failed

### ISSUE THREAD

**Issue by ghost** [maldevel/AES256#1]
Hello, 
I am trying to use your module, but I get false from Decrypt function. CryptDecrypt function causes error.

My decrypter and enrypter two seperate program. When I use the decrypt function inside the encrypter, it works. 

Do you have any idea about the problem?

**Comment by maldevel** [comment]
You have to use the same password and the same initialization vector on both sides (IV)!

**Comment by ghost** [comment]
Thanks for a quick reply.

So, after this function: _CryptGenRandom(*provider, blockSize, *iv)_
I need to save IV, right? Then I should use it in the decrypter?

**Comment by maldevel** [comment]
You have to send it over e.g. network using a simple base64 encoding, no need to be secret.

**Comment by ghost** [comment]
Thank you a lot. I saved the IV, then used with my decrypter and it worked. I am trying to write very simple program(for personal using), so it does not need to network connection, but I get the idea(finally).

Thanks again.
